import CashierTemplate from "@/components/CashierTemplate"
import MenuList from "../menuList"


export const metadata = {
   title: 'Transaksi | Ordering System',
   description: 'Generated by create next app',
}


type PropsLayout = {
   children: React.ReactNode
}


const RootLayout = ({ children }: PropsLayout) => {
   return (
       <CashierTemplate title="Transaksi" id="Transaksi" menuList={MenuList}>
           {children}
       </CashierTemplate>
   )
}

export default RootLayout