import ManagerTemplate from "@/components/ManagerTemplate"
import MenuList from "../menuList"

export const metadata = {
    title: 'Menu',
    description: 'Generated by create next app',
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
    return (
        <ManagerTemplate title="Menu" id="Menu"
            menuList={MenuList}>
            {children}
        </ManagerTemplate>
    )
}

export default RootLayout